package mappers

import (
	"time"

	"golang-social-media/apps/ecommerce-service/internal/domain/order"
)

// OrderModel represents the database model for Order
// This is defined here to avoid import cycle
type OrderModel struct {
	ID          string    `gorm:"column:id;type:uuid;primaryKey"`
	UserID      string    `gorm:"column:user_id;type:text;not null"`
	Status      string    `gorm:"column:status;type:text;not null"`
	TotalAmount float64   `gorm:"column:total_amount;type:decimal(10,2);not null"`
	CreatedAt   time.Time `gorm:"column:created_at;not null"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null"`
}

func (OrderModel) TableName() string {
	return "orders"
}

// OrderItemModel represents the database model for OrderItem
type OrderItemModel struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey"`
	OrderID   string    `gorm:"column:order_id;type:uuid;not null;index"`
	ProductID string    `gorm:"column:product_id;type:uuid;not null"`
	Quantity  int       `gorm:"column:quantity;type:integer;not null"`
	UnitPrice float64   `gorm:"column:unit_price;type:decimal(10,2);not null"`
	SubTotal  float64   `gorm:"column:sub_total;type:decimal(10,2);not null"`
	CreatedAt time.Time `gorm:"column:created_at;not null"`
}

func (OrderItemModel) TableName() string {
	return "order_items"
}

// OrderMapper maps between domain Order and persistence models
type OrderMapper struct{}

// NewOrderMapper creates a new OrderMapper
func NewOrderMapper() *OrderMapper {
	return &OrderMapper{}
}

// ToModel converts a domain Order to OrderModel and OrderItemModels
func (m *OrderMapper) ToModel(o order.Order) (OrderModel, []OrderItemModel) {
	orderModel := OrderModel{
		ID:          o.ID,
		UserID:      o.UserID,
		Status:      string(o.Status),
		TotalAmount: o.TotalAmount,
		CreatedAt:   o.CreatedAt,
		UpdatedAt:   o.UpdatedAt,
	}

	itemModels := make([]OrderItemModel, len(o.Items))
	for i, item := range o.Items {
		itemModels[i] = OrderItemModel{
			ID:        "", // Will be generated by DB
			OrderID:   o.ID,
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			SubTotal:  item.SubTotal,
			CreatedAt: o.CreatedAt,
		}
	}

	return orderModel, itemModels
}

// ToDomain converts OrderModel and OrderItemModels to domain Order
func (m *OrderMapper) ToDomain(orderModel OrderModel, itemModels []OrderItemModel) order.Order {
	orderItems := make([]order.OrderItem, len(itemModels))
	for i, item := range itemModels {
		orderItems[i] = order.OrderItem{
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			SubTotal:  item.SubTotal,
		}
	}

	return order.Order{
		ID:          orderModel.ID,
		UserID:      orderModel.UserID,
		Status:      order.Status(orderModel.Status),
		Items:       orderItems,
		TotalAmount: orderModel.TotalAmount,
		CreatedAt:   orderModel.CreatedAt,
		UpdatedAt:   orderModel.UpdatedAt,
	}
}

// ToDomainList converts a slice of orders to domain Orders
func (m *OrderMapper) ToDomainList(orders []OrderModel, itemsMap map[string][]OrderItemModel) []order.Order {
	result := make([]order.Order, len(orders))
	for i, orderModel := range orders {
		items := itemsMap[orderModel.ID]
		if items == nil {
			items = []OrderItemModel{}
		}
		result[i] = m.ToDomain(orderModel, items)
	}
	return result
}

