package mappers

import (
	"golang-social-media/apps/ecommerce-service/internal/domain/order"
	"golang-social-media/apps/ecommerce-service/internal/infrastructure/persistence/postgres"
)

// OrderMapper maps between domain Order and persistence models
type OrderMapper struct{}

// NewOrderMapper creates a new OrderMapper
func NewOrderMapper() *OrderMapper {
	return &OrderMapper{}
}

// ToModel converts a domain Order to OrderModel and OrderItemModels
func (m *OrderMapper) ToModel(o order.Order) (postgres.OrderModel, []postgres.OrderItemModel) {
	orderModel := postgres.OrderModel{
		ID:          o.ID,
		UserID:      o.UserID,
		Status:      string(o.Status),
		TotalAmount: o.TotalAmount,
		CreatedAt:   o.CreatedAt,
		UpdatedAt:   o.UpdatedAt,
	}

	itemModels := make([]postgres.OrderItemModel, len(o.Items))
	for i, item := range o.Items {
		itemModels[i] = postgres.OrderItemModel{
			ID:        "", // Will be generated by DB
			OrderID:   o.ID,
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			SubTotal:  item.SubTotal,
			CreatedAt: o.CreatedAt,
		}
	}

	return orderModel, itemModels
}

// ToDomain converts OrderModel and OrderItemModels to domain Order
func (m *OrderMapper) ToDomain(orderModel postgres.OrderModel, itemModels []postgres.OrderItemModel) order.Order {
	orderItems := make([]order.OrderItem, len(itemModels))
	for i, item := range itemModels {
		orderItems[i] = order.OrderItem{
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			SubTotal:  item.SubTotal,
		}
	}

	return order.Order{
		ID:          orderModel.ID,
		UserID:      orderModel.UserID,
		Status:      order.Status(orderModel.Status),
		Items:       orderItems,
		TotalAmount: orderModel.TotalAmount,
		CreatedAt:   orderModel.CreatedAt,
		UpdatedAt:   orderModel.UpdatedAt,
	}
}

// ToDomainList converts a slice of orders to domain Orders
func (m *OrderMapper) ToDomainList(orders []postgres.OrderModel, itemsMap map[string][]postgres.OrderItemModel) []order.Order {
	result := make([]order.Order, len(orders))
	for i, orderModel := range orders {
		items := itemsMap[orderModel.ID]
		if items == nil {
			items = []postgres.OrderItemModel{}
		}
		result[i] = m.ToDomain(orderModel, items)
	}
	return result
}

