package mappers

import (
	"golang-social-media/apps/auth-service/internal/domain/user"
	"golang-social-media/pkg/contracts/auth"
)

// UserDTOMapper maps between domain User and DTOs
type UserDTOMapper struct{}

// NewUserDTOMapper creates a new UserDTOMapper
func NewUserDTOMapper() *UserDTOMapper {
	return &UserDTOMapper{}
}

// ToRegisterResponse converts a domain User to RegisterResponse DTO
func (m *UserDTOMapper) ToRegisterResponse(u user.User) auth.RegisterResponse {
	return auth.RegisterResponse{
		ID:    u.ID,
		Email: u.Email,
		Name:  u.Name,
		// Password is intentionally excluded from DTO
	}
}

// ToProfileResponse converts a domain User to ProfileResponse DTO
func (m *UserDTOMapper) ToProfileResponse(u user.User) auth.ProfileResponse {
	return auth.ProfileResponse{
		ID:    u.ID,
		Email: u.Email,
		Name:  u.Name,
		// Password is intentionally excluded from DTO
	}
}

// ToLoginResponse converts user ID and token to LoginResponse DTO
func (m *UserDTOMapper) ToLoginResponse(userID, token string) auth.LoginResponse {
	return auth.LoginResponse{
		UserID: userID,
		Token:  token,
	}
}

// FromRegisterRequest converts RegisterRequest DTO to domain User
// Note: This creates a partial User (without ID), ID should be generated by application layer
func (m *UserDTOMapper) FromRegisterRequest(req auth.RegisterRequest) user.User {
	return user.User{
		Email:    req.Email,
		Password: req.Password,
		Name:     req.Name,
		// ID will be set by application layer
	}
}

// FromLoginRequest extracts email and password from LoginRequest
func (m *UserDTOMapper) FromLoginRequest(req auth.LoginRequest) (email, password string) {
	return req.Email, req.Password
}

