package postgres

import (
	"time"

	"golang-social-media/apps/ecommerce-service/internal/domain/order"
)

type OrderModel struct {
	ID          string    `gorm:"column:id;type:uuid;primaryKey"`
	UserID      string    `gorm:"column:user_id;type:text;not null"`
	Status      string    `gorm:"column:status;type:text;not null"`
	TotalAmount float64   `gorm:"column:total_amount;type:decimal(10,2);not null"`
	CreatedAt   time.Time `gorm:"column:created_at;not null"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null"`
}

func (OrderModel) TableName() string {
	return "orders"
}

type OrderItemModel struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey"`
	OrderID   string    `gorm:"column:order_id;type:uuid;not null;index"`
	ProductID string    `gorm:"column:product_id;type:uuid;not null"`
	Quantity  int       `gorm:"column:quantity;type:integer;not null"`
	UnitPrice float64   `gorm:"column:unit_price;type:decimal(10,2);not null"`
	SubTotal  float64   `gorm:"column:sub_total;type:decimal(10,2);not null"`
	CreatedAt time.Time `gorm:"column:created_at;not null"`
}

func (OrderItemModel) TableName() string {
	return "order_items"
}

func OrderModelFromDomain(o order.Order) (OrderModel, []OrderItemModel) {
	orderModel := OrderModel{
		ID:          o.ID,
		UserID:      o.UserID,
		Status:      string(o.Status),
		TotalAmount: o.TotalAmount,
		CreatedAt:   o.CreatedAt,
		UpdatedAt:   o.UpdatedAt,
	}

	itemModels := make([]OrderItemModel, len(o.Items))
	for i, item := range o.Items {
		itemModels[i] = OrderItemModel{
			ID:        "", // Will be generated by DB
			OrderID:   o.ID,
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			SubTotal:  item.SubTotal,
			CreatedAt: o.CreatedAt,
		}
	}

	return orderModel, itemModels
}

func (m OrderModel) ToDomain(items []OrderItemModel) order.Order {
	orderItems := make([]order.OrderItem, len(items))
	for i, item := range items {
		orderItems[i] = order.OrderItem{
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			SubTotal:  item.SubTotal,
		}
	}

	return order.Order{
		ID:          m.ID,
		UserID:      m.UserID,
		Status:      order.Status(m.Status),
		Items:       orderItems,
		TotalAmount: m.TotalAmount,
		CreatedAt:   m.CreatedAt,
		UpdatedAt:   m.UpdatedAt,
	}
}

